### ISSUE TITLE
can not install package

### ISSUE THREAD

**Issue by hr-sadooghi** [Ali-kh333/persianValidator-mobile#1]
This is a best package for mobile number jobs, such as validation and data gathering for Iran mobile numbers.
But when I want to install it with composer get the following error:
`
  [InvalidArgumentException]                                                                                                                                                             
  Could not find a version of package persian-validator/mobile matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.  
`

**Comment by alikhalilitari** [comment]
Package didn't have version so some errors may have been raised but it is fixed now and thanks for using my package
